# Generated by Django 4.2.6 on 2024-01-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_berita', models.CharField(max_length=8)),
                ('judul', models.CharField(max_length=150)),
                ('penulis', models.CharField(max_length=100)),
                ('tanggal', models.CharField(max_length=50)),
                ('waktu_posting', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berita.status')),
            ],
        ),
    ]
