# Generated by Django 4.2.6 on 2024-01-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='id_berita',
            new_name='kode_berita',
        ),
    ]
