# Generated by Django 4.2.6 on 2024-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_berita_foto_alter_berita_judul_alter_status_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='isi',
            field=models.TextField(default=''),
        ),
    ]
