# Generated by Django 5.0.1 on 2024-01-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_berita_isi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='kode_berita',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='waktu_posting',
        ),
        migrations.AlterField(
            model_name='berita',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
